name: analisis-estatico
on:
  push:
    branches:
      - dev
jobs:
  ci-cd-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.3.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: test and coverage
        run: npm run test:coverage
      - name: SonarCloud Scan
        uses: InnovacionTecnologicaCSP/infra-tpl-github-actions/sonar-analysis@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-organization: ${{ secrets.SONAR_ORGANIZATION }}
          sonar-project-key: 'InnovacionTecnologicaCSP_pro-insurance-and-assistance-msa'
